_TITLE "Dailies_Recorder"
DIM TASK AS STRING
DIM REWARDS AS STRING
DIM NOTES AS STRING
DIM SAVE_PATH AS STRING
DIM GIMME_RECORD AS STRING

MAIN:
CLS
COLOR 15
PRINT "Welcome to Dailies_Recorder"
COLOR 10
PRINT "Which Task?"
INPUT "> ", TASK
COLOR 13
PRINT "What Rewards?"
INPUT "> ", REWARDS
COLOR 14
PRINT "Extra Notes?"
INPUT "> ", NOTES
COLOR 11
PRINT "[SPACE] to do another, [BACKSPACE] to undo, or [ESC] to end"

DO
    K$ = INKEY$
    K$ = UCASE$(K$)
LOOP UNTIL K$ = CHR$(32) OR K$ = CHR$(27) OR K$ = CHR$(8)
IF K$ = CHR$(8) THEN GOTO MAIN

SAVE_PATH = "Dailies_Records.csv"

IF NOT _FILEEXISTS(SAVE_PATH) THEN
    OPEN SAVE_PATH FOR OUTPUT AS #1
    PRINT #1, "DATE,TASK,REWARD,NOTES"
    CLOSE #1
END IF

GIMME_RECORD = CHR$(34) + DATE$ + CHR$(34) + CHR$(44)
GIMME_RECORD = GIMME_RECORD + CHR$(34) + TASK + CHR$(34) + CHR$(44)
GIMME_RECORD = GIMME_RECORD + CHR$(34) + REWARDS + CHR$(34) + CHR$(44)
GIMME_RECORD = GIMME_RECORD + CHR$(34) + NOTES + CHR$(34)

OPEN SAVE_PATH FOR APPEND AS #1
PRINT #1, GIMME_RECORD
CLOSE #1

IF K$ = CHR$(32) THEN GOTO MAIN
IF K$ = CHR$(27) THEN END


